runtime: python27
threadsafe: true
api_version: 1
version: 0


handlers:
- url: /rest/.*
  script: main.APP

- url: /(.+)
  static_files: app/\1
  upload: app/.*
  http_headers: Access-Control-Allow-Origin: *
  http_headers: Access-Control-Allow-Headers: *
  http_headers: Access-Control-Allow-Methods: *

- url: .*
  script: main.app
  http_headers: Access-Control-Allow-Origin: *
  http_headers: Access-Control-Allow-Headers: *
  http_headers: Access-Control-Allow-Methods: *
