runtime: python27
threadsafe: true
api_version: 1
version: 0


handlers:

# - url: /fake_data.json
#   static_files: fake_data.json
#   upload: fake_data.json

- url: /(.+)
  static_files: app/\1
  upload: app/.*

- url: .*
  script: main.app
